# Generated by Django 3.2 on 2022-11-12 17:23

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовано ли', verbose_name='Публикация')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField(help_text='Введите только цифры, буквы латиницы, "-" и "_"', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='Слаг')),
                ('weight', models.IntegerField(default=100, help_text='Введите вес категории', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'default_related_name': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовано ли', verbose_name='Публикация')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField(help_text='Введите только цифры, буквы латиницы, "-" и "_"', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовано ли', verbose_name='Публикация')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('text', models.TextField(help_text='Введите описание товара', validators=[catalog.validators.validate_must_be_param], verbose_name='Описание товара')),
                ('upload', models.ImageField(blank=True, upload_to='uploads/%Y/%m', verbose_name='превью')),
                ('category', models.ForeignKey(help_text='Введите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(help_text='Введите тэг', related_name='items', to='catalog.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'default_related_name': 'items',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузить картинку', null=True, upload_to='', verbose_name='изображение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallary', to='catalog.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'галлерея',
                'default_related_name': 'gallary',
            },
        ),
    ]
