# Generated by Django 3.2 on 2022-11-23 16:31

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Введите описание товара', validators=[catalog.validators.validate_must_be_param], verbose_name='Описание товара'),
        ),
    ]
